/**
 * generated by Xtext 2.14.0
 */
package org.xtext.template.ide;

import org.xtext.template.ide.AbstractTemplateIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class TemplateIdeModule extends AbstractTemplateIdeModule {
}
