/**
 * generated by Xtext 2.14.0
 */
package org.xtext.template;

import org.xtext.template.TemplateStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TemplateStandaloneSetup extends TemplateStandaloneSetupGenerated {
  public static void doSetup() {
    new TemplateStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
