/**
 * generated by Xtext 2.14.0
 */
package org.xtext.template;

import org.xtext.template.AbstractTemplateRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class TemplateRuntimeModule extends AbstractTemplateRuntimeModule {
}
