/*
 * generated by Xtext 2.14.0
 */
package org.xtext.template.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTemplateScopeProvider extends DelegatingScopeProvider {
}
