/**
 * generated by Xtext 2.14.0
 */
package org.xtext.template.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.template.ui.AbstractTemplateUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class TemplateUiModule extends AbstractTemplateUiModule {
  public TemplateUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
